# Generated by Django 3.1.3 on 2020-12-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date_of_completion',
            field=models.DateTimeField(null=True),
        ),
    ]
