# Generated by Django 3.1.3 on 2020-12-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20201215_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='completed',
            field=models.BooleanField(),
        ),
    ]
